### ISSUE TITLE
increased tab amount

### ISSUE THREAD

**Issue by Siegfried0** [easonwong-de/Tab-Preview-On-Hover#12]
I recently remembered, that I had something like this add-on active a long time ago at way older firefox versions.
I really like the idea of preview images for tabs, since I sometimes work with a huge bulk of tabs that might cause me to loose track of what's actually open and where.

Sadly this tool is currently disabled in my collection, since I have no real usecase for it due to the limitation to 10 tabs.
I have currently 13 tabs open and still think this is pretty managable even without previews.
Not sure if I am alone with this opinion: For me the usecase of this add-on starts earliest with 20+ tabs - which is not supported, therefore currently it is not used at all.

My whish would be to increase the amount of tabs or make it configurable. My personal preference would be up to 100.
In that case one preview box centered in the middle of the screen (maybe also configurable in size and resolution?) would be perfect.

Any comments about the possibility to get such a feature?

Thank you and kind regards

**Comment by CennoxX** [comment]
The preview of tabs is now integrated in Firefox (for more than 10 tabs), one just needs to set browser.tabs.cardPreview.enabled in about:config. The appearance of this add-on feels a little cleaner than Firefox's integration though, maybe the customisations can be transferred to the new functionality, @easonwong-de?
