### ISSUE TITLE
Firefox 115.13.0esr (64) is not supported?

### ISSUE THREAD

**Issue by Confetolog** [easonwong-de/Tab-Preview-On-Hover#13]
1. Created a chrome folder in the profile folder
2. Saved file userChrome.css in this folder
3. Turned toolkit.legacyUserProfileCustomizations.stylesheets to true
4. Restart Firefox
5. Tab Preview On Hover Tab Preview On Hover does not work
![dc2e1422094f965d9dc431521b87e261](https://github.com/user-attachments/assets/e13256ed-64a0-4b14-b352-6f4586e92dcc)

**Comment by tyrohellion** [comment]
Yea it's broken on the newer versions of firefox as of right now

edit: as of 129.0 or later this is an officially supported feature

**Comment by easonwong-de** [comment]
Yup, tab preview is an officially supported feature now. This project is closing down.

Thank y’all for testing and have a good day!

**Comment by tyrohellion** [comment]
> Yup, tab preview is an officially supported feature now. This project is closing down.
> 
> 
> 
> Thank y’all for testing and have a good day!

Thank you for your work on this project over it's lifetime 🙂
