### ISSUE TITLE
Add Tab Info Alongside the Preview

### ISSUE THREAD

**Issue by VitalSkib** [easonwong-de/Tab-Preview-On-Hover#2]
Oh, this is a cool one.. 😎👍
I'm glad I could find this, thank you very much. 

Few question though.. 
Is it possible to improve it further? 
1. Hide tooltip on the tab hover. 
2. Add an additional field to the preview, with tab info. 
Similar to how it's implemented in the MS Edge and Google Chrome?
tia

![chrome_edge](https://user-images.githubusercontent.com/43848892/232488730-509427f4-380a-43c7-9c16-b2c552bf5d9a.png)

**Comment by easonwong-de** [comment]
Hi, thanks for trying the add-on & CSS theme out!

I’ve been thinking about adding tab info display since I started the project. It is presumably achievable, but there are still some technical issues in the way.

**Comment by VitalSkib** [comment]
> Hi, thanks for trying the add-on & CSS theme out!
> 
> I’ve been thinking about adding tab info display since I started the project. It is presumably achievable, but there are still some technical issues in the way.

Yeah, that would be cool too, I hope you will be able to figure it out eventually and it will be solved in the future. 
However, this is not the most important thing in this case, so.. 
Good luck and thanks again.

**Comment by easonwong-de** [comment]
@VitalSkib Tab info is added in v0.0.3. Feel free to test it out, and any feedback is welcomed!

**Comment by VitalSkib** [comment]
> @VitalSkib Tab info is added in v0.0.3. Feel free to test it out, and any feedback is welcomed!

Oh that's so cool.., thank you so much! 😎👍
The only thing that bothers me a little is the font size. 
The default window size is too small for my taste, so I increased it via CSS. 
But if I do that, then the font size increases too. 
Any ideas how to get around this?
tia

![2023_05_29_Firefox_Nightly](https://github.com/easonwong-de/Tab-Preview-On-Hover/assets/43848892/7975b517-0898-429d-9040-99195b268b3e)

**Comment by easonwong-de** [comment]
For now, there's no way to customize the design of what's in the preview box, because they are all rendered with JavaScript instead of CSS. But that also means they could be easily configured using an option page.

This may be the main theme of the next update.

**Comment by VitalSkib** [comment]
> For now, there's no way to customize the design of what's in the preview box, because they are all rendered with JavaScript instead of CSS. But that also means they could be easily configured using an option page.
> 
> This may be the main theme of the next update.

Ah, ok, I see. 
Thank you..

**Comment by easonwong-de** [comment]
In the next major update, the preview panel will be customizable. I’ll close this issue for now, please stay tuned :)
