### ISSUE TITLE
Allow Tab Being Suspended

### ISSUE THREAD

**Issue by easonwong-de** [easonwong-de/Tab-Preview-On-Hover#3]
> I have tested the new version and the problem has been fixed but at the cost of losing the option to keep tabs suspended until they are selected.
> 
> Unfortunately it interferes with one of the extensions I use (auto tab discard) making it unusable.

_Originally posted by @kaos-55 in https://github.com/easonwong-de/Tab-Preview-On-Hover/issues/1#issuecomment-1546685928_

**Comment by kaos-55** [comment]
Just to clarify one thing, it's not necessarily auto tab discard support but Firefox's built-in feature of not loading tabs until they are selected when you close and reopen the browser.

**Comment by easonwong-de** [comment]
@kaos-55 Thanks for the clarification. My current idea is providing two options – allowing tab being suspended & always reloading suspended tabs. Because the add-on can take a snapshot of a tab only when it is active, if tabs are allowed to be discarded, the favicon will be shown in the preview panel for suspended tabs instead.

**Comment by easonwong-de** [comment]
@kaos-55 With the newest patch v0.0.3, the add-on stopped forcing tabs to be active. The issue might be addressed now.

**Comment by kaos-55** [comment]
I have tried version 0.0.3 and the problem has been solved. Additionally, I have seen that the information from the tab has been added to the thumbnail.
Thank you for fixing it, I think the issue can be closed.
