### ISSUE TITLE
Downloads tabs without requesting

### ISSUE THREAD

**Issue by PhoenixIndigo** [easonwong-de/Tab-Preview-On-Hover#4]
This addon loads inactive tabs after rebooting Firefox and unloading tabs with addon [UnloadTabs](https://addons.mozilla.org/firefox/addon/unload-tabs/)!
[Visual Tabs](https://addons.mozilla.org/firefox/addon/visualtab/) & [Tip Tab](https://addons.mozilla.org/firefox/addon/tip-tab/) did not load inactive tabs!

**Comment by easonwong-de** [comment]
Same as #3
