### ISSUE TITLE
Right Links WE does not work because of Tab-Preview-On-Hover

### ISSUE THREAD

**Issue by PhoenixIndigo** [easonwong-de/Tab-Preview-On-Hover#5]
[Right Links WE](https://addons.mozilla.org/firefox/addon/right-links/) Configure to the opening of links with a long press of the left button in the background. And with your extension, another tab opens, if the link opens in a new window, and if not, it also goes into the main tab!

**Comment by easonwong-de** [comment]
@PhoenixIndigo Thanks for reporting this. I’ll remove the auto-reload function from the TPOH add-on, and this might fix most of the compatibility issues.

**Comment by easonwong-de** [comment]
@PhoenixIndigo The latest version v0.0.3 might fix the problem. If the issue still preserves, I’ll have a deeper look into it.

**Comment by PhoenixIndigo** [comment]
The problem remains, only now the double transition occurs after the button releases.
And the extension is not closed and does not delete, for some reason the previous version works.
Tell me what needs to be deleted!

**Comment by PhoenixIndigo** [comment]
I checked on the new profile [Right Links We](https://addons.mozilla.org/firefox/addon/right-links/) as it did not work, I will delete it.

**Comment by easonwong-de** [comment]
I installed Right Links WE and did some tests, but nothing seems to go wrong. Maybe you can check if Tab Preview On Hover is on its newest version.

**Comment by PhoenixIndigo** [comment]
And on the new profile 0.0.3 with chrome>userChrome.css does not work for me

**Comment by PhoenixIndigo** [comment]
![](https://github.com/easonwong-de/Tab-Preview-On-Hover/assets/107413021/5ab1f689-93ef-4141-a52b-dad2159b46df)
On the new profile does not work like on the old!

**Comment by PhoenixIndigo** [comment]
Tanks works

**Comment by easonwong-de** [comment]
Glad it works. If Tab Preview On Hover conflicts with any add-on, feel free to open new issues. If the preview box turns blank again, you can reöpen this issue: #1. Have a great day.

**Comment by PhoenixIndigo** [comment]
Junk Tap To Tab
