### ISSUE TITLE
URL-text of first tab on search bar

### ISSUE THREAD

**Issue by CennoxX** [easonwong-de/Tab-Preview-On-Hover#6]
Hi, probably a bug due to the new added title cards: now the location.host of my first tab is shown on the search bar (ctrl+f) - in the example below it is mail.google.com. If I deactivate your addon [Adaptive-Tab-Bar-Color](https://github.com/easonwong-de/Adaptive-Tab-Bar-Color) and restart the browser this seems to be gone (but I didn't test it that much), so maybe the problems are between the two?

I'm using
Tab-Preview-On-Hover 0.0.3
Firefox 114.0.2 (64-Bit)
Windows 10.0.19045 Build 19045

![grafik](https://github.com/easonwong-de/Tab-Preview-On-Hover/assets/6975881/a6c9e845-0914-444f-b23a-dd3654fe814b)

**Comment by easonwong-de** [comment]
@CennoxX This can be fixed with CSS theme. I’ll notify you when a new version is available.

**Comment by easonwong-de** [comment]
@CennoxX Please install the latest `userChrome.css` and try again. The issue should have been addressed.

**Comment by CennoxX** [comment]
Great, that worked, thanks for the fix!

**Comment by easonwong-de** [comment]
Glad to hear that. If there’s any further problem or suggestion, feel free to open a new issue.
