### ISSUE TITLE
A hint of the full name and preferably addresses

### ISSUE THREAD

**Issue by PhoenixIndigo** [easonwong-de/Tab-Preview-On-Hover#7]
[CSS theme](https://prod.outgoing.prod.webservices.mozgcp.net/v1/00623837bc6ceab4291499717063adabe8f5b0383f43cef303af0ea64a135d16/https%3A//raw.githubusercontent.com/easonwong-de/Tab-Preview-On-Hover/main/CSS%2520Theme/userChrome.css) Why did you turn off the hint of the full name of the tab, if it is cut in the preview, not like in Chrome (there is a complete name)? Plus, I added the address in the name.

**Comment by easonwong-de** [comment]
@PhoenixIndigo There’s a compromise bound to be made. When the tab title is short and not cut in the tab preview panel, the default tooltip is pure redundancy. But at the same time, it’s quite impractical to make the tab title roll across when it’s too long.

**Comment by PhoenixIndigo** [comment]
You do not hint at adding excess TitleBar instead of tips that I consider irreplaceable?

**Comment by easonwong-de** [comment]
It will of course be optimal if the preview panel can adjust its size so that the whole tab title can be displayed. I will try to achieve that, but in the meantime, you might need to reënable the tooltip if you find it irreplaceable.

**Comment by PhoenixIndigo** [comment]
In addition, the tabs after the tenth also need to be presented?

**Comment by PhoenixIndigo** [comment]
In addition, the tabs after the tenth also need to be presented

**Comment by easonwong-de** [comment]
I’ll say letting the preview panel adjust its size dynamically is difficult with the available API, so is balancing the performance whilst increasing the amount of the tab previews. But please don’t interpret it as I do not want to improve the add-on & CSS theme pack. Making the full tab title & URL visible and more tab previews available is undoubtedly ideal, just there are comprises to be made at the moment.

Any way, thank you for trying out the project and giving the suggestions. I’ll close the issue for now.
