### ISSUE TITLE
Add tooltips for tabs after the first ten

### ISSUE THREAD

**Issue by CennoxX** [easonwong-de/Tab-Preview-On-Hover#9]
Is it possible, to show the title card without image but with the tab info, for the eleventh tab and ongoing? That way, one could take a look at a more complete title and the url with a glance.

**Comment by easonwong-de** [comment]
Not very likely as far as I am aware. There are very few ways to transfer tab information to the Firefox UI. The tab info beneath the tab preview is actually a part of the image sent by the add-on to the Firefox UI.

**Comment by easonwong-de** [comment]
I may want to add something here: the tab tooltips in vanilla Firefox are actually a single HTML element that changes its position when the cursor hovers on different tabs. That means the tooltips will appear on all tabs or no tabs, depending on the CSS.
